os: linux
dist: bionic
language: java
jdk: openjdk11
python: 3.7 # for mkdocs
services: docker # for testcontainers

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

branches:
  except:
    - /^release-\d+\.\d+(\.\d+)?(-\S*)?$/

before_install:
  - "mkdir -p ~/.gradle"
  - "echo 'org.gradle.jvmargs=-Xmx1g -XX:MaxPermSize=256m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8' >> $HOME/.gradle/gradle.properties"
  - "echo 'org.gradle.configureondemand=true' >> $HOME/.gradle/gradle.properties"
  - "echo 'org.gradle.daemon=true' >> $HOME/.gradle/gradle.properties"
  - "echo 'org.gradle.parallel=true' >> $HOME/.gradle/gradle.properties"
  - "echo 'systemProp.jdk.tls.client.protocols=\"TLSv1,TLSv1.1,TLSv1.2\"' >> $HOME/.gradle/gradle.properties"

install: echo "skip 'gradle assemble' step"
script: ./gradlew build --scan --stacktrace
after_success: bash .scripts/travis/coverage.sh

# Release
deploy:
  skip_cleanup: true
  provider: script
  script: bash .scripts/travis/release.sh
  on:
    branch: master

# Cache some gradle folders
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Send notification to slack
notifications:
  slack: $SLACK
