site_name: sherlock-distributed-lock
site_description: Dostributed lock library for JVM
site_author: coditory
site_url: https://coditory.github.io/sherlock-distributed-lock
site_dir: build/docs

repo_name: coditory/sherlock-distributed-lock
repo_url: https://github.com/coditory/sherlock-distributed-lock

theme:
  name: 'material'
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: /assets/img/favicon.png
  logo:
    icon: "\uE80C"

plugins:
  - search
  - markdownextradata: {}
  - minify:
      minify_html: true

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version: '0.3.0'
  vcs_baseurl: https://github.com/coditory/sherlock-distributed-lock/blob/master
  social:
    - type: globe
      link: https://coditory.com
    - type: github-alt
      link: https://github.com/coditory/sherlock-distributed-lock
    - type: twitter
      link: https://twitter.com/coditory

# Site navigation
nav:
  - Home: index.md
  - Installation: installation.md
  - API: api.md
  - API:
      - Synchronous: api/synchronous.md
      - Reactor: api/reactor.md
      - RxJava: api/rxjava.md
  - Connectors: connectors.md
  - Connectors:
      - MongoDb: connectors/mongo.md
      - SQL: connectors/sql.md
      - InMemory: connectors/inmem.md
  - Lock Types: lock-types.md
  - Lock Duration: lock-duration.md
  - Migrator: migrator.md
  - Testing: testing.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
