version: "3.8"
name: sherlock_dbs
services:
  mongo:
    image: mongo:7
    container_name: sherlock_dbs-mongo
    restart: on-failure
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
  mysql:
    image: mysql:8
    container_name: sherlock_dbs-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      # root username is 'root'
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  postgres:
    image: postgres:11
    container_name: sherlock_dbs-postgres
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
