name: Docs

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "mkdocs-requirements.txt"
  workflow_run:
    workflows: ["Release"]
    branches: [master]
    types: [completed]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs -r mkdocs-requirements.txt
      - run: mkdocs gh-deploy --force
