name: Docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "docs/src/**"
      - "docs/mkdocs.yml"
      - "docs/mkdocs-requirements.txt"

jobs:
  docs:
    uses: coditory/workflows/.github/workflows/docs.yml@v1
    secrets: inherit
